MOUSEKEY_ENABLE = yes    # Mouse keys
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
#RGBLIGHT_ENABLE = no
#RGB_MATRIX_ENABLE = yes 
#RGB_MATRIX_CUSTOM_USER = yes 
